const fs = require('node:fs');
const path = require('node:path');
const p = path.join(__dirname, '..', 'src', 'App.tsx');
let s = fs.readFileSync(p, 'utf8');
s = s.replace("const [showLabels, setShowLabels] = useState(true);", "const [showLabels, setShowLabels] = useState(false);");
s = s.replace("const [showRadius, setShowRadius] = useState(true);", "const [showRadius, setShowRadius] = useState(false);");
s = s.replace("const [showStateColors, setShowStateColors] = useState(true);", "const [showStateColors, setShowStateColors] = useState(false);");
s = s.replace("const [showCityDots, setShowCityDots] = useState(true);", "const [showCityDots, setShowCityDots] = useState(false);");
s = s.replace("const [showGlowPoints, setShowGlowPoints] = useState(true);", "const [showGlowPoints, setShowGlowPoints] = useState(false);");
s = s.replace('<div className="sb-lbl">SERVICE METRIC</div>', '<div className="sb-lbl">SERVICE PRESENCE</div>');
s = s.replace("className:'dark-tiles'", "className:'network-map-tiles'");
fs.writeFileSync(p, s);
console.log('prebuild fixes applied');
