import { createRoot } from "react-dom/client";
import "./mapboxLeafletRuntime";
import "./mapToolsCommandPanel";
import "./rightPanelCompactor";
import "./liveFinderDriveTools";
import "./sidebarCommandFixes";
import App from "./App";
import "./index.css";
import "./professional-overrides.css";
import "./professional-hardening.css";
import "./liquid-glass-theme.css";
import "./live-finder-ux.css";
import "./mapbox-intelligence.css";
import "./live-finder-eta-actions.css";
import "./luminous-shell-fixes.css";
import "./sidebar-control-fixes.css";
import "./modal-popup-fixes.css";
import "./modal-content-polish.css";
import "./performance-safety.css";

createRoot(document.getElementById("root")!).render(<App />);
